module.exports = {
  waypoints: {
    START: 'start',
    CLAIMED_STATE_PENSION: 'claimed-state-pension',
    STATE_PENSION_NOT_CLAIMED: 'state-pension-not-claimed',
    CHILDREN_LIVING_WITH_YOU: 'children-living-with-you',
    CLAIM_INCLUDES_CHILDREN: 'claim-includes-children-living-with-you',
    LIVE_ENGLAND_SCOTLAND_WALES: 'live-england-scotland-wales',
    DO_NOT_LIVE_UK: 'do-not-live-uk',
    YOUR_NATIONALITY: 'your-nationality',
    DATE_OF_BIRTH: 'date-of-birth',
    TOO_YOUNG_TO_CLAIM: 'too-young-to-claim',
    LIVE_WITH_PARTNER: 'live-with-partner',
    PARTNER_HOUSING_BENEFIT: 'partner-housing-benefit',
    PARTNER_AGREE: 'partner-agree',
    DONE_PARTNER: 'done-partner',
    DATE_OF_CLAIM: 'date-of-claim',
    CLAIMANT_DETAILS: 'claimant-details',
    CONTACT_FORMATS: 'contact-formats',
    PARTNER_DETAILS: 'partner-details',
    PARTNER_NATIONALITY: 'partner-nationality',
    CARE_HOME: 'care-home',
    POSTCODE_LOOKUP: 'postcode-lookup',

    WHERE_YOU_LIVE_ADDRESS_POSTCODE_LOOKUP: 'postcode-lookup',
    WHERE_YOU_LIVE_ADDRESS_MANUAL: 'address-manual',
    WHERE_YOU_LIVE_ADDRESS_SELECT: 'address-choice',
    WHERE_YOU_LIVE_ADDRESS_HIDDEN: '__home_address__',

    LETTERS_HOME: 'letters-home',

    LETTERS_ADDRESS_POSTCODE_LOOKUP: 'letters-postcode-lookup',
    LETTERS_ADDRESS_MANUAL: 'letters-address',
    LETTERS_ADDRESS_SELECT: 'address-letters-choice',
    LETTERS_ADDRESS_HIDDEN: '__letters_address__',

    LIVES_WITH_YOU: 'lives-with-you',
    RENT_COUNCIL_TAX: 'rent-council-tax',
    HOME_OWNERSHIP: 'home-ownership',
    SERVICE_CHARGES: 'service-charges',
    HOME_LOAN: 'home-loan',
    SHARE_RENT_MORTGAGE: 'share-rent-mortgage',

    PRIVATE_PENSIONS: 'private-pensions',
    BENEFITS: 'benefits',

    HRT_CITIZEN_RETURNED_TO_UK: 'returned-to-uk',
    HRT_CITIZEN_NATIONALITY_DETAILS: 'nationality-details',
    HRT_CITIZEN_UK_SPONSORSHIP: 'uk-sponsorship',
    HRT_CITIZEN_SPONSORSHIP_DETAILS: 'sponsorship-details',
    HRT_CITIZEN_SPONSOR_ADDRESS_POSTCODE_LOOKUP: 'sponsor-address-postcode-lookup',
    HRT_CITIZEN_SPONSOR_ADDRESS_MANUAL: 'sponsor-address-manual',
    HRT_CITIZEN_SPONSOR_ADDRESS_SELECT: 'sponsor-address-select',
    HRT_CITIZEN_ASYLUM_SEEKER: 'asylum-seeker',
    HRT_CITIZEN_SPONSOR_ADDRESS_HIDDEN: '__sponsor-address__',

    HRT_PARTNER_RETURNED_TO_UK: 'partner-returned-to-uk',
    HRT_PARTNER_NATIONALITY_DETAILS: 'partner-nationality-details',
    HRT_PARTNER_UK_SPONSORSHIP: 'partner-uk-sponsorship',
    HRT_PARTNER_SPONSORSHIP_DETAILS: 'partner-sponsorship-details',
    HRT_PARTNER_SPONSOR_ADDRESS_POSTCODE_LOOKUP: 'partner-sponsor-address-postcode-lookup',
    HRT_PARTNER_SPONSOR_ADDRESS_MANUAL: 'partner-sponsor-address-manual',
    HRT_PARTNER_SPONSOR_ADDRESS_SELECT: 'partner-sponsor-address-select',
    HRT_PARTNER_ASYLUM_SEEKER: 'partner-asylum-seeker',
    HRT_PARTNER_SPONSOR_ADDRESS_HIDDEN: '__partner-sponsor-address__',

    CHECK_YOUR_ANSWERS: 'check-your-answers',
    WHAT_HAPPENS_NEXT: 'what-happens-next',
  },

  origins: {
    APPLY: 'apply-for-pension-credit',
  },
};
